name: Pull request
on:
  pull_request:
  workflow_dispatch:
jobs:
  composer-install:
    name: Composer Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
      - name: Validate composer files
        run: composer validate --no-check-all --strict
